#!/bin/bash
commit_msg_file="$1"
commit_msg=$(head -n1 "$commit_msg_file")
conventional_regex="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-zA-Z0-9_-]+\))?: .+"
if ! [[ $commit_msg =~ $conventional_regex ]]; then
  echo "Commit message is not a conventional commit. Commit aborted."
  exit 1
fi
