services:
  test-postgres:
    image: postgres:15-alpine
    container_name: youth-attendance-test-db
    environment:
      POSTGRES_DB: test_youth_attendance
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"  # Use 5433 to avoid conflicts with any existing PostgreSQL
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    command: >
      postgres 
      -c shared_preload_libraries=pg_stat_statements
      -c max_connections=200
      -c shared_buffers=128MB
      -c effective_cache_size=256MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_youth_attendance"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  test_postgres_data: